const mongoose = require("mongoose");
const { Schema } = mongoose;

const conn = mongoose.createConnection(process.env.MONGO_URL_PERSONAL);

const limpiezaMensualSchema = new Schema({
  fecha: { type: Date, required: true },
  area_cuartos_pisos: Boolean,
  area_cuartos_muelle_observaciones: String,
  area_cuartos_muelle: Boolean,
  responsable: { type: String, required: true },
  area_cuartos_cortinas_observaciones: String,
  area_cuartos_pisos_observaciones: String,
  area_cuartos_ventiladores: Boolean,
  area_cuartos_ventiladores_observaciones: String,
  area_cuartos_cortinas: Boolean,
  area_recepcion_pisos: Boolean,
  area_recepcion_vigas_observaciones: String,
  area_recepcion_canecas_observaciones: String,
  area_recepcion_filtro_observaciones: String,
  area_recepcion_banda: Boolean,
  area_recepcion_anjeos: Boolean,
  area_recepcion_cortinas_observaciones: String,
  area_recepcion_estibadores_observaciones: String,
  area_recepcion_tanqueInmersion_observaciones: String,
  area_recepcion_desverdizado_observaciones: String,
  area_recepcion_oficina_observaciones: String,
  area_recepcion_estibas_observaciones: String,
  area_recepcion_filtro: Boolean,
  area_recepcion_tanque: Boolean,
  area_recepcion_oficina: Boolean,
  area_recepcion_cortinas: Boolean,
  area_recepcion_banda_observaciones: String,
  area_recepcion_tanque_observaciones: String,
  area_recepcion_soporte: Boolean,
  area_recepcion_soporte_observaciones: String,
  area_recepcion_pisos_observaciones: String,
  area_recepcion_muelles: Boolean,
  area_recepcion_vigas: Boolean,
  area_recepcion_estibadores: Boolean,
  area_recepcion_anjeos_observaciones: String,
  area_recepcion_desverdizado: Boolean,
  area_recepcion_canecas: Boolean,
  area_recepcion_muelles_observaciones: String,
  area_recepcion_tanqueInmersion: Boolean,
  area_recepcion_estibas: Boolean,
  area_lavado_rodillosLavado: Boolean,
  area_lavado_rodillos_observaciones: String,
  area_lavado_extractores_observaciones: String,
  area_lavado_rodillos: Boolean,
  area_lavado_rodillosLavado_observaciones: String,
  area_lavado_extractoresSecado_observaciones: String,
  area_lavado_paredes: Boolean,
  area_lavado_anjeos_observaciones: String,
  area_lavado_extractores: Boolean,
  area_lavado_extractoresSecado: Boolean,
  area_lavado_anjeos: Boolean,
  area_lavado_paredes_observaciones: String,
  area_produccion_oficina: Boolean,
  area_produccion_herramientas_observaciones: String,
  area_produccion_cuarto_observaciones: String,
  area_produccion_ventiladoresPiso_observaciones: String,
  area_produccion_paredes: Boolean,
  area_produccion_escaleras_observaciones: String,
  area_produccion_rodillosEncerados_observaciones: String,
  area_produccion_oficina_observaciones: String,
  area_produccion_cuarto: Boolean,
  area_produccion_estibadores_observaciones: String,
  area_produccion_ventiladores: Boolean,
  area_produccion_laboratorio_observaciones: String,
  area_produccion_escaleras: Boolean,
  area_produccion_extractores_observaciones: String,
  area_produccion_pisos_observaciones: String,
  area_produccion_extractores: Boolean,
  area_produccion_filtro_observaciones: String,
  area_produccion_anjeos: Boolean,
  area_produccion_bandejas: Boolean,
  area_produccion_ventiladoresPiso: Boolean,
  area_produccion_canecas: Boolean,
  area_produccion_laboratorio: Boolean,
  area_produccion_filtro: Boolean,
  area_produccion_estibadores: Boolean,
  area_produccion_herramientas: Boolean,
  area_produccion_soportes_observaciones: String,
  area_produccion_clasificadora: Boolean,
  area_produccion_carritos_observaciones: String,
  area_produccion_rodillosEncerados: Boolean,
  area_produccion_anjeos_observaciones: String,
  area_produccion_ventiladores_observaciones: String,
  area_produccion_pisos: Boolean,
  area_produccion_canecas_observaciones: String,
  area_produccion_cilindro: Boolean,
  area_produccion_clasificadora_observaciones: String,
  area_produccion_carritos: Boolean,
  area_produccion_paredes_observaciones: String,
  area_produccion_bandejas_observaciones: String,
  area_produccion_soportes: Boolean,
  area_produccion_cilindro_observaciones: String,
  area_pasillo_pisos: Boolean,
  area_pasillo_pisos_observaciones: String,
  area_carton_esstibadores: Boolean,
  area_carton_pisos: Boolean,
  area_carton_estibadores_observaciones: String,
  area_carton_pisos_observaciones: String,
  area_sociales_comedorExterior_observaciones: String,
  area_sociales_paredes: Boolean,
  area_sociales_comedorExterior: Boolean,
  area_sociales_lockers_observaciones: String,
  area_sociales_pisos: Boolean,
  area_sociales_nevera: Boolean,
  area_sociales_hornos: Boolean,
  area_sociales_comedor_observaciones: String,
  area_sociales_exteriores_observaciones: String,
  area_sociales_canecas_observaciones: String,
  area_sociales_exteriores: Boolean,
  area_sociales_nevera_observaciones: String,
  area_sociales_comedor: Boolean,
  area_sociales_lockers: Boolean,
  area_sociales_anjeos_observaciones: String,
  area_sociales_pisos_observaciones: String,
  area_sociales_paredes_observaciones: String,
  area_sociales_canecas: Boolean,
  area_sociales_hornos_observaciones: String,
  area_sociales_anjeos: Boolean,
});

const LimpiezaMensual = conn.model("LimpiezaMensual", limpiezaMensualSchema);


module.exports.LimpiezaMensual = LimpiezaMensual;