const mongoose = require("mongoose");
const { Schema } = mongoose;

const conn = mongoose.createConnection(process.env.MONGO_URL_PERSONAL);

const limpiezaSchema = new Schema({
  area_social_vestieres: Boolean,
  area_social_vestieres_observaciones: String,
  area_social_mesones: Boolean,
  area_social_mesones_observaciones: String,
  area_social_microondas_observaciones: String,
  area_social_microondas: Boolean,
  area_recepcion_tanque: Boolean,
  area_recepcion_muelles_observaciones: String,
  area_recepcion_estibadores_observaciones: String,
  area_recepcion_tanque_observaciones: String,
  area_recepcion_muelles: Boolean,
  area_recepcion_estibadores: Boolean,
  area_lavado_rodillos_tunel_observaciones: String,
  area_lavado_equipo: Boolean,
  area_lavado_equipo_observaciones: String,
  area_lavado_piso: Boolean,
  area_lavado_piso_observaciones: String,
  area_lavado_desbalinadora: Boolean,
  area_lavado_rodillos_tunel: Boolean,
  area_lavado_paredes_observaciones: String,
  area_lavado_rodillos: Boolean,
  area_lavado_desbalinadora_observaciones: String,
  area_lavado_paredes: Boolean,
  area_lavado_rodillos_observaciones: String,
  area_proceso_herramientas: Boolean,
  area_proceso_basculas_observaciones: String,
  area_proceso_estibadores_observaciones: String,
  area_proceso_pisos_observaciones: String,
  area_proceso_bandejas_clasificadora_observaciones: String,
  area_proceso_rodillos_clasificadora_observaciones: String,
  area_proceso_estibadores: Boolean,
  area_proceso_basculas: Boolean,
  area_proceso_modulo_encerado: Boolean,
  area_proceso_modulo_encerado_observaciones: String,
  area_proceso_herramientas_observaciones: String,
  area_proceso_rodillos_cera: Boolean,
  area_proceso_rodillos_tunel_2: Boolean,
  area_proceso_rodillos_clasificadora: Boolean,
  area_proceso_bandejas_clasificadora: Boolean,
  area_proceso_rodillos_cera_observaciones: String,
  area_proceso_paredes_observaciones: String,
  area_proceso_pisos: Boolean,
  area_proceso_paredes: Boolean,
  area_proceso_rodillos_tunel_2_observaciones: String,
  area_laboratorio_utensilios_observaciones: String,
  area_laboratorio_paredes_observaciones: String,
  area_laboratorio_piso_observaciones: String,
  area_laboratorio_utensilios: Boolean,
  area_laboratorio_meson_observaciones: String,
  area_laboratorio_paredes: Boolean,
  area_laboratorio_cajon_utensilios_observaciones: String,
  area_laboratorio_cajon_utensilios: Boolean,
  area_laboratorio_piso: Boolean,
  area_laboratorio_meson: Boolean,
  area_almacenamiento_pisos_observaciones: String,
  area_almacenamiento_malla: Boolean,
  area_almacenamiento_estibadores_observaciones: String,
  area_almacenamiento_paredes: Boolean,
  area_almacenamiento_pisos: Boolean,
  area_almacenamiento_paredes_observaciones: String,
  area_almacenamiento_malla_observaciones: String,
  area_almacenamiento_estibadores: Boolean,
  area_sanitarios_lavamanos: Boolean,
  area_sanitarios_piso: Boolean,
  area_sanitarios_recipiente: Boolean,
  area_sanitarios_piso_observaciones: String,
  area_sanitarios_paredes_observaciones: String,
  area_sanitarios_recipiente_observaciones: String,
  area_sanitarios_sanitarios: Boolean,
  area_sanitarios_paredes: Boolean,
  area_sanitarios_lavamanos_observaciones: String,
  area_sanitarios_sanitarios_observaciones: String,
  area_comunes_alrededores: Boolean,
  area_comunes_cuarto_residuos: Boolean,
  area_comunes_cuarto_residuos_observaciones: String,
  area_comunes_alrededores_observaciones: String,
  fecha: Date
});

const LimpiezaDesinfeccionPlanta = conn.model("LimpiezaDesinfeccionPlanta", limpiezaSchema);


module.exports.LimpiezaDesinfeccionPlanta = LimpiezaDesinfeccionPlanta;